sudo: required

services:
    - docker


before_install:
    - docker build -t mamedyahyayev/react-docker -f Dockerfile.dev .


script:
    - docker run mamedyahyayev/react-docker npm run test -- --coverage
    