sudo: required

services:
    - docker


before_install:
    - docker build -t mamedyahyayev/react-docker -f Dockerfile.dev .


script:
    - docker run -e CI=true mamedyahyayev/react-docker npm run test
    